// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: shared/proto/redirect.proto

package redirectpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLongURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLongURLRequest) Reset() {
	*x = GetLongURLRequest{}
	mi := &file_shared_proto_redirect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLongURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLongURLRequest) ProtoMessage() {}

func (x *GetLongURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_redirect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLongURLRequest.ProtoReflect.Descriptor instead.
func (*GetLongURLRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_redirect_proto_rawDescGZIP(), []int{0}
}

func (x *GetLongURLRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type GetLongURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLongURLResponse) Reset() {
	*x = GetLongURLResponse{}
	mi := &file_shared_proto_redirect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLongURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLongURLResponse) ProtoMessage() {}

func (x *GetLongURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_redirect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLongURLResponse.ProtoReflect.Descriptor instead.
func (*GetLongURLResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_redirect_proto_rawDescGZIP(), []int{1}
}

func (x *GetLongURLResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_shared_proto_redirect_proto protoreflect.FileDescriptor

const file_shared_proto_redirect_proto_rawDesc = "" +
	"\n" +
	"\x1bshared/proto/redirect.proto\x12\bredirect\"2\n" +
	"\x11GetLongURLRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"/\n" +
	"\x12GetLongURLResponse\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl2Z\n" +
	"\x0fRedirectService\x12G\n" +
	"\n" +
	"GetLongURL\x12\x1b.redirect.GetLongURLRequest\x1a\x1c.redirect.GetLongURLResponseB\x19Z\x17shared/proto/redirectpbb\x06proto3"

var (
	file_shared_proto_redirect_proto_rawDescOnce sync.Once
	file_shared_proto_redirect_proto_rawDescData []byte
)

func file_shared_proto_redirect_proto_rawDescGZIP() []byte {
	file_shared_proto_redirect_proto_rawDescOnce.Do(func() {
		file_shared_proto_redirect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_redirect_proto_rawDesc), len(file_shared_proto_redirect_proto_rawDesc)))
	})
	return file_shared_proto_redirect_proto_rawDescData
}

var file_shared_proto_redirect_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_redirect_proto_goTypes = []any{
	(*GetLongURLRequest)(nil),  // 0: redirect.GetLongURLRequest
	(*GetLongURLResponse)(nil), // 1: redirect.GetLongURLResponse
}
var file_shared_proto_redirect_proto_depIdxs = []int32{
	0, // 0: redirect.RedirectService.GetLongURL:input_type -> redirect.GetLongURLRequest
	1, // 1: redirect.RedirectService.GetLongURL:output_type -> redirect.GetLongURLResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_redirect_proto_init() }
func file_shared_proto_redirect_proto_init() {
	if File_shared_proto_redirect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_redirect_proto_rawDesc), len(file_shared_proto_redirect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_redirect_proto_goTypes,
		DependencyIndexes: file_shared_proto_redirect_proto_depIdxs,
		MessageInfos:      file_shared_proto_redirect_proto_msgTypes,
	}.Build()
	File_shared_proto_redirect_proto = out.File
	file_shared_proto_redirect_proto_goTypes = nil
	file_shared_proto_redirect_proto_depIdxs = nil
}
