// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: shared/proto/shortener.proto

package shortenerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortURLRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LongUrl         string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	CustomShortCode *string                `protobuf:"bytes,2,opt,name=custom_short_code,json=customShortCode,proto3,oneof" json:"custom_short_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateShortURLRequest) Reset() {
	*x = CreateShortURLRequest{}
	mi := &file_shared_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLRequest) ProtoMessage() {}

func (x *CreateShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLRequest.ProtoReflect.Descriptor instead.
func (*CreateShortURLRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortURLRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *CreateShortURLRequest) GetCustomShortCode() string {
	if x != nil && x.CustomShortCode != nil {
		return *x.CustomShortCode
	}
	return ""
}

type CreateShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLResponse) Reset() {
	*x = CreateShortURLResponse{}
	mi := &file_shared_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLResponse) ProtoMessage() {}

func (x *CreateShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLResponse.ProtoReflect.Descriptor instead.
func (*CreateShortURLResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortURLResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

var File_shared_proto_shortener_proto protoreflect.FileDescriptor

const file_shared_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x1cshared/proto/shortener.proto\x12\tshortener\"y\n" +
	"\x15CreateShortURLRequest\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12/\n" +
	"\x11custom_short_code\x18\x02 \x01(\tH\x00R\x0fcustomShortCode\x88\x01\x01B\x14\n" +
	"\x12_custom_short_code\"7\n" +
	"\x16CreateShortURLResponse\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode2i\n" +
	"\x10ShortenerService\x12U\n" +
	"\x0eCreateShortURL\x12 .shortener.CreateShortURLRequest\x1a!.shortener.CreateShortURLResponseB\x1aZ\x18shared/proto/shortenerpbb\x06proto3"

var (
	file_shared_proto_shortener_proto_rawDescOnce sync.Once
	file_shared_proto_shortener_proto_rawDescData []byte
)

func file_shared_proto_shortener_proto_rawDescGZIP() []byte {
	file_shared_proto_shortener_proto_rawDescOnce.Do(func() {
		file_shared_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_shortener_proto_rawDesc), len(file_shared_proto_shortener_proto_rawDesc)))
	})
	return file_shared_proto_shortener_proto_rawDescData
}

var file_shared_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_shortener_proto_goTypes = []any{
	(*CreateShortURLRequest)(nil),  // 0: shortener.CreateShortURLRequest
	(*CreateShortURLResponse)(nil), // 1: shortener.CreateShortURLResponse
}
var file_shared_proto_shortener_proto_depIdxs = []int32{
	0, // 0: shortener.ShortenerService.CreateShortURL:input_type -> shortener.CreateShortURLRequest
	1, // 1: shortener.ShortenerService.CreateShortURL:output_type -> shortener.CreateShortURLResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_shortener_proto_init() }
func file_shared_proto_shortener_proto_init() {
	if File_shared_proto_shortener_proto != nil {
		return
	}
	file_shared_proto_shortener_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_shortener_proto_rawDesc), len(file_shared_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_shortener_proto_goTypes,
		DependencyIndexes: file_shared_proto_shortener_proto_depIdxs,
		MessageInfos:      file_shared_proto_shortener_proto_msgTypes,
	}.Build()
	File_shared_proto_shortener_proto = out.File
	file_shared_proto_shortener_proto_goTypes = nil
	file_shared_proto_shortener_proto_depIdxs = nil
}
