// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: shared/proto/token.proto

package tokenpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NextIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextIDReq) Reset() {
	*x = NextIDReq{}
	mi := &file_shared_proto_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextIDReq) ProtoMessage() {}

func (x *NextIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextIDReq.ProtoReflect.Descriptor instead.
func (*NextIDReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_token_proto_rawDescGZIP(), []int{0}
}

type NextIDRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextIDRes) Reset() {
	*x = NextIDRes{}
	mi := &file_shared_proto_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextIDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextIDRes) ProtoMessage() {}

func (x *NextIDRes) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextIDRes.ProtoReflect.Descriptor instead.
func (*NextIDRes) Descriptor() ([]byte, []int) {
	return file_shared_proto_token_proto_rawDescGZIP(), []int{1}
}

func (x *NextIDRes) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_shared_proto_token_proto protoreflect.FileDescriptor

const file_shared_proto_token_proto_rawDesc = "" +
	"\n" +
	"\x18shared/proto/token.proto\"\v\n" +
	"\tNextIDReq\"\x1b\n" +
	"\tNextIDRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id20\n" +
	"\fTokenService\x12 \n" +
	"\x06NextID\x12\n" +
	".NextIDReq\x1a\n" +
	".NextIDResB\x16Z\x14shared/proto/tokenpbb\x06proto3"

var (
	file_shared_proto_token_proto_rawDescOnce sync.Once
	file_shared_proto_token_proto_rawDescData []byte
)

func file_shared_proto_token_proto_rawDescGZIP() []byte {
	file_shared_proto_token_proto_rawDescOnce.Do(func() {
		file_shared_proto_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_token_proto_rawDesc), len(file_shared_proto_token_proto_rawDesc)))
	})
	return file_shared_proto_token_proto_rawDescData
}

var file_shared_proto_token_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_token_proto_goTypes = []any{
	(*NextIDReq)(nil), // 0: NextIDReq
	(*NextIDRes)(nil), // 1: NextIDRes
}
var file_shared_proto_token_proto_depIdxs = []int32{
	0, // 0: TokenService.NextID:input_type -> NextIDReq
	1, // 1: TokenService.NextID:output_type -> NextIDRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_token_proto_init() }
func file_shared_proto_token_proto_init() {
	if File_shared_proto_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_token_proto_rawDesc), len(file_shared_proto_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_token_proto_goTypes,
		DependencyIndexes: file_shared_proto_token_proto_depIdxs,
		MessageInfos:      file_shared_proto_token_proto_msgTypes,
	}.Build()
	File_shared_proto_token_proto = out.File
	file_shared_proto_token_proto_goTypes = nil
	file_shared_proto_token_proto_depIdxs = nil
}
